### ISSUE TITLE
check values against fig 2 of Gibbons et al 2005

### ISSUE THREAD

**Issue by dankelley** [dankelley/wave_attenuation#2]
![Screen Shot 2019-07-09 at 9 31 15 AM](https://user-images.githubusercontent.com/99469/60888137-782d3480-a22c-11e9-8f60-9158a3b82bcc.png)

**Comment by catevans** [comment]
App looks great! No typos from what I see. Some results from clicking around:

**Depth = 20, Sensor Height = 0**
**Click 1**: Period: 8.0s, Pressure Factor: 0.46, Wave Length: 89.4m 
**Click 2**: Period: 10.1s, Pressure Factor: 0.63, Wave Length: 122.2m
**Click 3**: Period: 4.0s, Pressure Factor: 0.013, Wave Length: 24.9m


**Depth = 70, Sensor Height = 5**
**Click 1**: Period: 10.0s, Pressure Factor: 0.12, Wave Length: 155.7m
**Click 2**: Period: 4.1s, Pressure Factor: 1.3e-07, Wave Length: 25.6m
**Click 3**: Period: 6.0s, Pressure Factor: 0.00092, Wave Length: 56.1m

**Depth = 10, Sensor Height = 0**
**Click 1**: Period: 2.0s, Pressure Factor: 6.9e-05, Wave Length: 6.1m
**Click 2**: Period: 8.1s, Pressure Factor: 0.71, Wave Length: 71.5m
**Click 3**: Period: 11.4s, Pressure Factor: 0.85, Wave Length: 106.7m

**Comment by dankelley** [comment]
Hm, so the results seem very different, if I'm reading the graphs right. If you're in the office, it might be helpful to chat for a few minutes.

**Comment by catevans** [comment]
I'm currently working offsite but could bike over?

**Comment by dankelley** [comment]
No need -- I was reading the fig  2 graph wrong. I think things are ok.

In the attached, I'm looking at the 5-s line that crosses the 0.01 pressure factor line about (by eye) about 32m.  On the app part of the screenshot, you can see that my click is giving 0.01 at a period of 5s. So I think all is okay.  I'll close this now. Thanks!

![Screen Shot 2019-07-09 at 10 51 38 AM](https://user-images.githubusercontent.com/99469/60893636-a5cbab00-a237-11e9-91f6-bd314cacd37d.png)
